services:
  # postgres database
  postgres:
    image: postgres:15
    container_name: elt_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

# pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: elt_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin:/var/lib/pgadmin

# extract
  extract:
    image: engineerbee/extractor:latest 
    container_name: elt_extractor
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./extract/data:/app/data
    restart: always

# dbt
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.0
    container_name: elt_dbt
    depends_on:
    - postgres
    env_file:
    - .env
    volumes:
    - ./dbt:/usr/app
    - ~/.dbt:/root/.dbt
    working_dir: /usr/app
    entrypoint: ["/bin/sh", "-c"]
    command: ["tail -f /dev/null"]

    
# metabase
  metabase:
    image: metabase/metabase
    container_name: elt_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: ${MB_DB_FILE}
    volumes:
      - ./metabase-data:/metabase.db
    depends_on:
      - postgres

volumes:
  pgdata:

  